# Generated by Django 2.2.12 on 2021-03-10 15:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
